import { Salon } from "@/types/salon.type";

export const sampleSalons: Salon[] = [
  {
    id: 1,
    name: "Chien",
    email: "chienlag1702@gmail.com",
    status: "active",
    description: "wfe",
    address: "Quy Nhon",
    phone: "097817739",
    logo: "https://serapool.fra1.cdn.digitaloceanspaces.com/media/4749/what-is-spa-serapool.jpg",
  },
  {
    id: 2,
    name: "Spa Beauty",
    email: "spa.beauty@gmail.com",
    status: "inactive",
    description: "High-end beauty treatments",
    address: "Da Nang",
    phone: "0912345678",
    logo: "logo_spa_beauty",
  },
  {
    id: 3,
    name: "Hair Magic",
    email: "hair.magic@gmail.com",
    status: "active",
    description: "Top-notch hair care services",
    address: "Ho Chi Minh City",
    phone: "0987654321",
    logo: "logo_hair_magic",
  },
  {
    id: 4,
    name: "Luxury Salon",
    email: "luxury.salon@gmail.com",
    status: "active",
    description: "Premium salon experience",
    address: "Hanoi",
    phone: "0909090909",
    logo: "logo_luxury_salon",
  },
  {
    id: 5,
    name: "Elegance Spa",
    email: "elegance.spa@gmail.com",
    status: "inactive",
    description: "Relax and rejuvenate",
    address: "Hai Phong",
    phone: "0888888888",
    logo: "logo_elegance_spa",
  },
];
